//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPlayerQuiz.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserQuiz()
        {
            this.QuizAnswers = new HashSet<QuizAnswer>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public int QuizId { get; set; }
        public System.DateTime Registeredon { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizAnswer> QuizAnswers { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}
